# Generated by Django 5.0.6 on 2024-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('format', models.CharField(choices=[('png', 'PNG'), ('jpeg', 'JPEG'), ('jpg', 'JPG'), ('ico', 'ICO'), ('bmp', 'BMP'), ('tiff', 'TIFF'), ('webp', 'WEBP')], default='png', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
